version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    ports:
      - '8080:8080'
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 12345
      DB_NAME: WhiteShop
      DB_PORT: 5432
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - bot.env

  db:
    image: postgres:14-alpine
    container_name: telegram_bot_db
    environment:
      POSTGRES_DB: WhiteShop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: